apiVersion: apps/v1
kind: Deployment
metadata:
  name: dso-demo
  labels:
    app: dso-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dso-demo
  template:
    metadata:
      labels:
        app: dso-demo
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/role: 'dso-demo'
        vault.hashicorp.com/agent-inject-secret-database: 'secret/dso-demo/database'
        vault.hashicorp.com/agent-inject-template-database: |
          {{- with secret "secret/dso-demo/database" -}}
          mysql -u {{ .Data.data.user }} -p {{ .Data.data.password }} -h database:3306 mydb
          {{- end -}}
    spec:
      serviceAccountName: dso-demo
      containers:
        - name: dso-demo
          image: salimgrayaa/dso-demo
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
